version: '3.8'
services:
  mongo:
    image: mongo
    restart: always

  trocio:
    container_name: trocio
    image: node:18-alpine
    depends_on:
      - mongo
    command: sh -c "apk add g++ make py3-pip && npm i && npm run dev"
    ports:
      - 5173:5173
    working_dir: /app
    volumes:
      - ./:/app
