// Generated by https://quicktype.io

export interface OpenCageResult {
  documentation: string
  licenses: License[]
  rate: Rate
  results: Result[]
  status: Status
  stay_informed: StayInformed
  thanks: string
  timestamp: Timestamp
  total_results: number
}

export interface License {
  name: string
  url: string
}

export interface Rate {
  limit: number
  remaining: number
  reset: number
}

export interface Result {
  annotations: Annotations
  bounds: Bounds
  components: Components
  confidence: number
  formatted: string
  geometry: Geometry
}

export interface Annotations {
  DMS: Dms
  MGRS: string
  Maidenhead: string
  Mercator: Mercator
  OSM: Osm
  UN_M49: UnM49
  callingcode: number
  currency: Currency
  flag: string
  geohash: string
  qibla: number
  roadinfo: Roadinfo
  sun: Sun
  timezone: Timezone
  what3words: What3Words
  wikidata: string
}

export interface Dms {
  lat: string
  lng: string
}

export interface Mercator {
  x: number
  y: number
}

export interface Osm {
  edit_url: string
  note_url: string
  url: string
}

export interface UnM49 {
  regions: { [key: string]: string }
  statistical_groupings: StatisticalGrouping[]
}

export enum StatisticalGrouping {
  Ledc = 'LEDC',
  Medc = 'MEDC',
}

export interface Currency {
  alternate_symbols: string[]
  decimal_mark: DecimalMark
  format?: string
  html_entity: string
  iso_code: string
  iso_numeric: string
  name: string
  smallest_denomination: number
  subunit?: string
  subunit_to_unit: number
  symbol: string
  symbol_first: number
  thousands_separator: DecimalMark
}

export enum DecimalMark {
  DecimalMark = '.',
  Empty = ',',
  Purple = ' ',
}

export interface Roadinfo {
  drive_on: DriveOn
  speed_in: SpeedIn
  road?: string
}

export enum DriveOn {
  Left = 'left',
  Right = 'right',
}

export enum SpeedIn {
  KMH = 'km/h',
}

export interface Sun {
  rise: Rise
  set: Rise
}

export interface Rise {
  apparent: number
  astronomical: number
  civil: number
  nautical: number
}

export interface Timezone {
  name: string
  now_in_dst: number
  offset_sec: number
  offset_string: string
  short_name: string
}

export interface What3Words {
  words: string
}

export interface Bounds {
  northeast: Geometry
  southwest: Geometry
}

export interface Geometry {
  lat: number
  lng: number
}

export interface Components {
  'ISO_3166-1_alpha-2': string
  'ISO_3166-1_alpha-3': string
  'ISO_3166-2'?: string[]
  _category: Category
  _type: string
  continent: Continent
  country: string
  country_code: string
  political_union?: string
  state?: string
  county?: string
  municipality?: string
  postcode?: string
  region?: string
  state_code?: string
  town?: string
  county_code?: string
  city?: string
  neighbourhood?: string
  post_office?: string
  road?: string
  waterway?: string
  industrial?: string
  province?: string
  village?: string
}

export enum Category {
  Government = 'government',
  NaturalWater = 'natural/water',
  Place = 'place',
}

export enum Continent {
  Asia = 'Asia',
  Europe = 'Europe',
  SouthAmerica = 'South America',
}

export interface Status {
  code: number
  message: string
}

export interface StayInformed {
  blog: string
  twitter: string
}

export interface Timestamp {
  created_http: string
  created_unix: number
}
