openapi: 3.0.1
info:
  title: Trocio
  description: 'API de Trocio'
  contact:
    email: info@troc.io
  version: 1.0.0
servers:
  - url: http://localhost:5001
    description: server local
  - url: https://localhost:3000/api
    description: server local atteint à travers via proxy
components:
  schemas:
    UserBase:
      $ref: 'user.yml#/components/schemas/UserBase'
    User:
      $ref: 'user.yml#/components/schemas/User'
    UserPublic:
      $ref: 'user.yml#/components/schemas/UserPublic'
    UserParticipant:
      $ref: 'user.yml#/components/schemas/UserParticipant'
    TrocBase:
      $ref: 'troc.yml#/components/schemas/TrocBase'
    Troc:
      $ref: 'troc.yml#/components/schemas/Troc'
    TrocUserResum:
      $ref: 'troc.yml#/components/schemas/TrocUserResum'
tags:
  - name: user
    description: Methodes relatives aux utilisateurs
  - name: troc
    description: Methodes relatives aux trocs
paths:
  /users:
    post:
      tags:
        - user
      summary: Création d'un compte utilisateur
      operationId: createUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserBase'
      responses:
        200:
          description: Utilisateur nouvellement créé
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
  /trocs:
    get:
      tags:
        - troc
      summary: Récupère des trocs
      operationId: getTrocs
      responses:
        200:
          description: Liste de trocs
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TrocBase'
  /trocs/resum:
    get:
      tags:
        - troc
      summary: Récupère le résumé de l'activité d'un participant
      operationId: getTrocResum
      parameters:
        - in: query
          name: trocId
          required: true
          schema:
            type: string
        - in: query
          name: userId
          required: true
          schema:
            type: string
      responses:
        200:
          description: Résumé de l'activité d'un participant
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TrocUserResum'
