openapi: 3.0.1
info:
  title: Trocio
  description: 'API de Trocio'
  contact:
    email: info@troc.io
  version: 1.0.0
servers:
  - url: http://localhost:5001
    description: server local
  - url: https://localhost:3000/api
    description: server local atteint à travers via proxy
components:
  schemas:
    TrocBase:
      $ref: 'troc.yml#/components/schemas/TrocBase'
    Troc:
      $ref: 'troc.yml#/components/schemas/Troc'
    TrocUserResume:
      $ref: 'troc.yml#/components/schemas/TrocUserResume'
tags:
  - name: troc
    description: Methodes relatives au troc
paths:
  /trocs:
    get:
      tags:
        - troc
      summary: Récupère des trocs
      operationId: getTrocs
      responses:
        200:
          description: Liste de trocs
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TrocBase'
