components:
  parameters:
    queryUser:
      in: query
      name: userId
      required: true
      schema:
        type: string
    queryTroc:
      in: query
      name: trocId
      required: true
      schema:
        type: string
    querySkip:
      in: query
      name: skip
      schema:
        type: number
    queryLimit:
      in: query
      name: limit
      schema:
        type: number
    pathTarif:
      in: path
      name: tarifId
      required: true
      schema:
        type: string
    pathTroc:
      in: path
      name: trocId
      required: true
      schema:
        type: string
    pathUser:
      in: path
      name: userId
      required: true
      schema:
        type: string
    pathArticle:
      in: path
      name: articleId
      required: true
      schema:
        type: string

  schemas:
    Success:
      type: object
      properties:
        success:
          type: boolean
        message:
          type: string
    Error:
      type: object
      properties:
        error:
          type: boolean
        message:
          type: string
    Timestamp:
      type: object
      properties:
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
    DataBase:
      type: object
      properties:
        _id:
          type: string
        _v:
          type: number
