components:
  schemas:
    Timestamp:
      type: object
      properties:
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
    DataBase:
      type: object
      properties:
        _id:
          type: string
        _v:
          type: number
