openapi: '3.0.2'
components:
  schemas:
    PaymentCreate:
      type: object
      properties:
        acceptor:
          type: string
        user:
          type: string
        troc:
          type: string
        amount:
          type: number
        message:
          type: string
    Payment:
      allOf:
        - $ref: '#/components/schemas/PaymentCreate'
        - $ref: 'meta.yml#/components/schemas/Timestamp'
        - $ref: 'meta.yml#/components/schemas/DataBase'
  responses:
    200_Payment:
      description: Un payement
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Payment'
    200_Payments:
      description: Liste de payements
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/Payment'
