openapi: '3.0.2'
components:
  schemas:
    Period:
      type: object
      properties:
        open:
          type: string
        close:
          type: string
        name:
          type: string
          enum:
            - 'open'
            - 'deposit'
            - 'recovery'
            - 'sale'
    Tarif:
      type: object
      properties:
        name:
          type: string
        bydefault:
          type: boolean
        apply:
          description: Participants sur lesquels le tarif est appliqué
          type: array
          items:
            type: string
        margin:
          type: number
        fee:
          type: array
          items:
            type: object
            properties:
              price:
                type: number
              value:
                type: number
        maxarticles:
          type: number
    TrocBase:
      type: object
      properties:
        creator:
          description: A valider
          type: string
        name:
          type: string
        description:
          type: string
        is_try:
          type: boolean
        address:
          type: string
        location:
          type: object
          properties:
            lat:
              type: number
            lng:
              type: number
        schedule:
          type: array
          items:
            $ref: '#/components/schemas/Period'
        society:
          type: string
        societyweb:
          type: string
    Troc:
      allOf:
        - $ref: 'meta.yml#/components/schemas/Timestamp'
        - $ref: 'meta.yml#/components/schemas/DataBase'
        - $ref: '#/components/schemas/TrocBase'
        - type: object
          properties:
            tag:
              type: object
              properties:
                width:
                  type: number
                height:
                  type: number
                padding:
                  type: number
                border:
                  type: boolean
            admin:
              type: array
              items:
                type: string
            cashier:
              type: array
              items:
                type: string
            articlelastref:
              type: number
            articles:
              type: object
            subscriber:
              type: number
            creator:
              type: string
            trader:
              type: array
              items:
                type: object
                properties:
                  prefix:
                    type: string
                  user:
                    type: string
            tarif:
              type: array
              items:
                $ref: '#/components/schemas/Tarif'
            isClosed:
              type: boolean
            id:
              description: Todo supprimer???
              type: string
            isAdmin:
              type: boolean
            isCashier:
              type: boolean
            isSubscribed:
              type: boolean
    TrocLookupUser:
      allOf:
        - $ref: '#/components/schemas/Troc'
        - type: object
          properties:
            creator:
              $ref: 'user.yml#/components/schemas/UserParticipant'
            admin:
              type: array
              items:
                $ref: 'user.yml#/components/schemas/UserParticipant'
            trader:
              type: array
              items:
                type: object
                properties:
                  prefix:
                    type: string
                  user:
                    $ref: 'user.yml#/components/schemas/UserParticipant'
            cashier:
              type: array
              items:
                $ref: 'user.yml#/components/schemas/UserParticipant'
            tarif:
              type: array
              items:
                allOf:
                  - $ref: '#/components/schemas/Tarif'
                  - type: object
                    properties:
                      apply:
                        type: array
                        items:
                          $ref: 'user.yml#/components/schemas/UserParticipant'
    TrocUserSpec:
      type: object
      properties:
        user:
          type: string
        troc:
          type: string
    TrocUserResum:
      type: object
      properties:
        user:
          type: string
        balance:
          type: number
        providedCount:
          type: number
        providedSum:
          type: number
        feeSum:
          type: number
        soldSum:
          type: number
        marginSum:
          type: number
        purchasesCount:
          type: number
        purchasesSum:
          type: number
        paymentsCount:
          type: number
        paymentsSum:
          type: number
    TrocState:
      type: object
      properties:
        articlesProposed:
          type: array
          items:
            $ref: 'article.yml#/components/schemas/Article'
        articlesBuyed:
          type: array
          items:
            $ref: 'article.yml#/components/schemas/Article'
        payments:
          type: array
          items:
            $ref: 'payment.yml#/components/schemas/Payment'
