on:
  workflow_call:

jobs:
  client:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
          cache: 'npm'
      - run: npm ci
      - run: npm run build:routify
      - run: npm run build:vite
      - name: Upload client artifact
        uses: actions/upload-artifact@v2
        with:
          name: client
          path: dist
