on:
  workflow_call:

jobs:
  client:
    runs-on: ubuntu-latest
    env:
      VITE_TROCIO_GOOGLE_CLIENT_ID: '188691377562-pns5mmusaf024gtt8m19nigri7evng73.apps.googleusercontent.com'
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: latest
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'pnpm'
      - run: pnpm install --frozen-lockfile
      - run: pnpm run build:routify
      - run: pnpm run build:vite
      - name: Upload client artifact
        uses: actions/upload-artifact@v3
        with:
          name: client
          path: dist
  server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: latest
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'pnpm'
      - run: pnpm install --frozen-lockfile
      - run: pnpm run build:server
      - name: Upload server artifact
        uses: actions/upload-artifact@v3
        with:
          name: server
          path: server
      - name: Upload package artifact
        uses: actions/upload-artifact@v3
        with:
          name: package
          path: |
            package.json
            package-lock.json
            ecosystem.config.js
