name: Trocio CI Labo

on:
  push:
    branches: [master, dev]

jobs:
  deploy:
    environment: Nestor - Labo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Copy codebase in trocio-tmp
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          source: '.'
          target: './trocio-tmp'

      - name: Deploy /trocio
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            . .profile
            cd trocio-tmp
            pnpm install --frozen-lockfile
            pnpm build
            cd ..
            rm -rf trocio
            mv trocio-tmp trocio
            cd trocio
            pnpm serve
