# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Trocio CI Test

on:
  push:
    branches: [dev-vite]

jobs:
  build-client:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
          cache: 'npm'
      - run: npm ci
      - run: npm run build:routify
      - run: npm run build:vite
      - name: Upload client artifact
        uses: actions/upload-artifact@v2
        with:
          name: client
          path: dist
  build-server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
          cache: 'npm'
      - run: npm ci
      - run: npm run build:server

      - name: Upload server artifact
        uses: actions/upload-artifact@v2
        with:
          name: server
          path: server

      - name: Upload package artifact
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: |
            package.json
            package-lock.json
            ecosystem.config.js

  deploy:
    needs: [build-server, build-client]
    environment: 'Nestor - Labo'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Download artifact server
        uses: actions/download-artifact@v2
        with:
          name: server
          path: trocio/server

      - name: Download artifact client
        uses: actions/download-artifact@v2
        with:
          name: client
          path: trocio/dist

      - name: Download artifact package
        uses: actions/download-artifact@v2
        with:
          name: package
          path: trocio

      - name: Display structure of downloaded files
        run: ls -R
        working-directory: trocio

      - name: Remove folder /trocio
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: rm -rf trocio

      - name: Copy artifacts
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          source: 'trocio'
          target: './'

      - name: Test package.json
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd trocio
            cat package.json

      - name: Install npm dependencies
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            . .profile
            cd trocio
            npm ci --production

      - name: Restart server
        uses: appleboy/ssh-action@master
        env:
          TROCIO_ADMIN: ${{ secrets.TROCIO_ADMIN }}
          TROCIO_API_PORT: ${{ secrets.TROCIO_API_PORT }}
          TROCIO_DB: ${{ secrets.TROCIO_DB }}
          TROCIO_FRONT_PORT: ${{ secrets.TROCIO_FRONT_PORT }}
          TROCIO_OCD_API_KEY: ${{ secrets.TROCIO_OCD_API_KEY }}
          TROCIO_SECRET_STRING_COOKIE: ${{ secrets.TROCIO_SECRET_STRING_COOKIE }}
          TROCIO_SMTP_PASS: ${{ secrets.TROCIO_SMTP_PASS }}
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          envs: TROCIO_ADMIN,TROCIO_DB,TROCIO_SECRET_STRING_COOKIE,TROCIO_SMTP_PASS,TROCIO_API_PORT,TROCIO_FRONT_PORT,TROCIO_OCD_API_KEY
          script: |
            . .profile
            cd trocio
            npm run serve
