# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Trocio CI Test

on:
  push:
    branches: [dev-vite]

jobs:
  build-client:
    if: ${{ false }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
          cache: 'npm'
      - run: npm ci
      - run: npm run build:client
      - name: Upload client
        uses: actions/upload-artifact@v2
        with:
          name: client
          path: dist
  build-server:
    if: ${{ false }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
          cache: 'npm'
      - run: npm ci
      - run: npm run build:server
      - name: Upload server
        uses: actions/upload-artifact@v2
        with:
          name: server
          path: server
  deploy:
    # needs: [build-client, build-server]
    runs-on: ubuntu-latest
    steps:
      - name: LOG-test
        shell: bash
        run: echo ${{ secrets.SSH_HOST }}
      - name: Connection ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            whoami
            ls -al
