# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Trocio CI Test

on:
  push:
    branches: [dev-vite]

jobs:
  build-client:
    if: ${{ false }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
          cache: 'npm'
      - run: npm ci
      - run: npm run build:client
      - name: Upload client artifact
        uses: actions/upload-artifact@v2
        with:
          name: client
          path: trocio/dist
  build-server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
          cache: 'npm'
      - run: npm ci
      - run: npm run build:server
      - name: Upload server artifact
        uses: actions/upload-artifact@v2
        with:
          name: server
          path: trocio/dist
      - name: Upload package artifact
        uses: actions/upload-artifact@v2
        with:
          name: package.json
          path: trocio/package.json
  deploy:
    needs: build-server
    environment: 'Nestor - Labo'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Reset folder /trocio
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            rm -rf trocio
            mkdir trocio

      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          path: trocio

      - name: Display structure of downloaded files
        run: ls -R
        working-directory: trocio

      - name: Copy artifacts
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          source: 'trocio'
          target: 'trocio'

      - name: Install npm dependencies
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd trocio
            npm ci

      - name: Restart server
        uses: appleboy/ssh-action@master
        env:
          TROCIO_ADMIN: ${{ secrets.TROCIO_ADMIN }}
          TROCIO_DB: ${{ secrets.TROCIO_DB }}
          TROCIO_SECRET_STRING_COOKIE: ${{ secrets.TROCIO_SECRET_STRING_COOKIE }}
          TROCIO_SMTP_PASS: ${{ secrets.TROCIO_SMTP_PASS }}
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          envs: TROCIO_ADMIN,TROCIO_DB,TROCIO_SECRET_STRING_COOKIE,TROCIO_SMTP_PASS
          script: |
            pm2 start trocio/server/server.js --update-env
