# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Trocio CI Test

on:
  push:
    branches: [dev-vite]

jobs:
  build-client:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
          cache: 'npm'
      - run: npm ci
      - run: npm run build:client
  build-server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
          cache: 'npm'
      - run: npm ci
      - run: npm run build:server
  deploy:
    needs: [build-client, build-server]
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        run: echo '😜'
